{% set name = "qiskit" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qiskit-{{ version }}.tar.gz
  sha256: 5a440d82007c32d4d6d3dbe75c279f78ba8f5052369af988f85020820dffa68a

build:
  ignore_run_exports:
    # Qiskit uses the Python stable C API/ABI and does not link to libpython
    - python
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - typing_extensions
    - rustworkx >=0.15.0
    - python
    - numpy <3,>=1.17
    - scipy >=1.5
    - sympy >=1.3
    - dill >=0.3
    - python-dateutil >=2.8.0
    - stevedore >=3.0.0
    - python-symengine <0.14,>=0.11
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - python-constraint >=1.4
    - seaborn >=0.9.0
    - z3-solver >=4.7
    - qiskit-terra >=1.0  # qiskit 1.0 no longer depends on qiskit-terra and must not be installed with it. qiskit-terra >=1.0 should never be published.

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip
    # Temporary workaround for missing dependency of pbr which is a dependency of stevedore
    # Can be removed after https://github.com/conda-forge/pbr-feedstock/pull/53 is merged
    - setuptools

about:
  home: https://www.ibm.com/quantum/qiskit
  summary: SDK for working with quantum computers at the level of extended quantum circuits, operators, and primitives.
  doc_url: https://docs.quantum.ibm.com
  dev_url: https://github.com/Qiskit/qiskit
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
