{% set name = "qiskit" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-{{ version }}.tar.gz
  sha256: c549383fc057c11eb1dcf89949fe751800797d149ef0115c40e406d9718d9d31

build:
  ignore_run_exports:
    # Qiskit uses the Python stable C API/ABI and does not link to libpython
    - python
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - typing-extensions
    - rustworkx >=0.14.0
    - python
    - numpy <2,>=1.17
    - scipy >=1.5
    - sympy >=1.3
    - dill >=0.3
    - python-dateutil >=2.8.0
    - stevedore >=3.0.0
    - python-symengine >=0.11
    - zstd  # Temporary workaround for https://github.com/conda-forge/python-symengine-feedstock/issues/50
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - python-constraint >=1.4
    - seaborn >=0.9.0
    - z3-solver >=4.7
    - qiskit-terra >=1.0  # qiskit 1.0 no longer depends on qiskit-terra and must not be installed with it. qiskit-terra >=1.0 should never be published.

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qiskit.org/
  summary: Software for developing quantum computing programs
  doc_url: https://qiskit.org/documentation/index.html
  dev_url: https://github.com/Qiskit/qiskit
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
