context:
  name: qiskit
  python_name: qiskit
  version: "2.1.2"
  python_min: "3.9"

package:
  name: qiskit
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/qiskit-${{ version }}.tar.gz
  sha256: fd3fe5b212053e18aea66b3903face62e25d7ba0aebd0aa68ea1fb4f14b220e3

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv
  skip: not (match(python, python_min ~ ".*") and is_abi3)
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - python-abi3
    - setuptools
    - setuptools-rust
  run:
    - dill >=0.3
    - numpy <3,>=1.17
    - python
    - rustworkx >=0.15.0
    - scipy >=1.5
    - stevedore >=3.0.0
    - typing_extensions

  run_constraints:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - python-constraint >=1.4
    # Technically, Qiskit has a <0.14 constraint, but symengine is only used
    # for loading old files saved in the qpy format and it seems better not to
    # impede users using symengine for other use cases in the same environment
    # as Qiskit than to support loading old qpy files (the user can still
    # manually install symengine <0.14 if needed; this is just about not
    # preventing the user from using a newer version).
    - python-symengine >=0.11
    - seaborn >=0.9.0
    - sympy >=1.3

tests:
  - python:
      imports:
        - qiskit
      python_version: ["${{ python_min ~ '.*' }}"]
  - script:
      - pip check
    requirements:
      run:
        - pip

about:
  homepage: https://www.ibm.com/quantum/qiskit
  summary: SDK for working with quantum computers at the level of extended quantum circuits, operators, and primitives.
  documentation: https://quantum.cloud.ibm.com/docs/en/guides
  repository: https://github.com/Qiskit/qiskit
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
